### ISSUE TITLE
Unable to open scrapping.log

### ISSUE THREAD

**Issue by lucumon** [zbyna/Media-Stub-Kodi-Creator#2]
I get that error with all versions.
If I skip that pop-up, then I get "List index (-1) out of bounds" error.

**Comment by lucumon** [comment]
Solved executing it as administrator (Win10)

**Comment by zbyna** [comment]
Great! I have prepared a video how to fix it while ago: https://youtu.be/3oQOzVDyoOI

**Comment by lucumon** [comment]
Oh wow! Thanks for your work :)!
